### ISSUE TITLE
ble_gateway: homeassistant.service from esphoe automation

### ISSUE THREAD

**Issue by tbaumann** [myhomeiot/esphome-components#15]
Is there any reason why this shouldn't work?
```yaml
  on_ble_advertise:
    then:
    - logger.log: BLE  !lambda return packet;
    - homeassistant.service:
        service: ble_monitor.parse_data
        data:
          packet: !lambda return packet;
          gateway_id: $device_name
```

It seems a bit unnecessary to rely on a homeassistant automation to listen to the event first
