### ISSUE TITLE
ble_gateway: Document discovery mode

### ISSUE THREAD

**Issue by tbaumann** [myhomeiot/esphome-components#16]
I just came across the option `discovery:  true`

I think this is pretty much the default behavior anyone would expect of a BLE gateway. And it's a lot more easy to understand than the currently documented method with the text_sensor.

I think this option should be mentioned in the documentation and examples.

My minimal config is this. 
```yaml
ble_gateway:
  id: $device_name
  discovery: true
  on_ble_advertise:
    then:
    - homeassistant.service:
        service: ble_monitor.parse_data
        data:
          packet: !lambda return packet;
          gateway_id: $device_name
```

Add this to any esphome device and receive BLE advertisements. Simple.
