### ISSUE TITLE
Error "READ_CHAR_EVT error reading char at handle (33), status (5)" when reading battery value from soocare.toothbrush.x3

### ISSUE THREAD

**Issue by mihsu81** [myhomeiot/esphome-components#21]
Hi @myhomeiot,
When trying to read the value of the battery characteristic of a soocare.toothbrush.x3 I see the below warning and the value is not read: ```[W] | [myhomeiot_ble_client:194] | [EF:A8:A8:06:8C:E6] READ_CHAR_EVT error reading char at handle (33), status (5)```
With nRF Connect I can see the value is _**17%**_. Is **_%_** the cause of the issue, and how can I remove it?

Thank in advance.

<html>
<body>

23:01:25 | [I] | [myhomeiot_ble_client:032] | [EF:A8:A8:06:8C:E6] Connecting
-- | -- | -- | --
23:01:25 | [I] | [myhomeiot_ble_client:087] | [EF:A8:A8:06:8C:E6] Connected successfully, app_id (1)
23:01:25 | [W] | [myhomeiot_ble_client:194] | [EF:A8:A8:06:8C:E6] READ_CHAR_EVT error reading char at handle (33), status (5)
23:01:25 | [I] | [myhomeiot_ble_client:042] | [EF:A8:A8:06:8C:E6] Disconnecting

</body>
</html>

The configuration is:
```yaml
myhomeiot_ble_client:
  - mac_address: EF:A8:A8:06:8C:E6
    service_uuid: '180F'
    characteristic_uuid: '2A19'
    update_interval: 24h
    on_value:
      then:
        lambda: |-
          id(mihai_s_toothbrush_battery).publish_state(x[0]);
```
