### ISSUE TITLE
Error compiling on ESPHome 2025.6.0

### ISSUE THREAD

**Issue by lazyandproud** [myhomeiot/esphome-components#36]
INFO ESPHome 2025.6.0
INFO Reading configuration /config/esphome/ble-tracker.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing ble-tracker (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.4
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.3.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.6
Compiling .pioenvs/ble-tracker/src/esphome/components/ble_gateway/ble_gateway.cpp.o
Compiling .pioenvs/ble-tracker/src/esphome/components/esp32_ble/ble_advertising.cpp.o
Compiling .pioenvs/ble-tracker/src/esphome/components/esp32_ble/ble_uuid.cpp.o
Compiling .pioenvs/ble-tracker/src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp.o
src/esphome/components/ble_gateway/ble_gateway.cpp: In member function 'virtual bool esphome::ble_gateway::BLEGateway::parse_device(const esphome::esp32_ble_tracker::ESPBTDevice&)':
src/esphome/components/ble_gateway/ble_gateway.cpp:62:56: error: 'const class esphome::esp32_ble_tracker::ESPBTDevice' has no member named 'get_scan_result'
     auto packet = scan_result_to_hci_packet_hex(device.get_scan_result());
                                                        ^~~~~~~~~~~~~~~
*** [.pioenvs/ble-tracker/src/esphome/components/ble_gateway/ble_gateway.cpp.o] Error 1
========================== [FAILED] Took 3.04 seconds ==========================

**Comment by Alexamig** [comment]
Gives an error when compiling.
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.4
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.3.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
Compiling .pioenvs/esp32-ble-gateway/src/esphome/components/ble_gateway/ble_gateway.cpp.o
Compiling .pioenvs/esp32-ble-gateway/src/esphome/components/mdns/mdns_rp2040.cpp.o
Compiling .pioenvs/esp32-ble-gateway/src/esphome/components/network/util.cpp.o
Compiling .pioenvs/esp32-ble-gateway/src/esphome/components/ota/ota_backend.cpp.o
src/esphome/components/ble_gateway/ble_gateway.cpp: In member function 'virtual bool esphome::ble_gateway::BLEGateway::parse_device(const esphome::esp32_ble_tracker::ESPBTDevice&)':
src/esphome/components/ble_gateway/ble_gateway.cpp:62:56: error: 'const class esphome::esp32_ble_tracker::ESPBTDevice' has no member named 'get_scan_result'
     auto packet = scan_result_to_hci_packet_hex(device.get_scan_result());
                                                        ^~~~~~~~~~~~~~~
*** [.pioenvs/esp32-ble-gateway/src/esphome/components/ble_gateway/ble_gateway.cpp.o] Error 1

**Comment by myhomeiot** [comment]
**Update:** PR https://github.com/esphome/esphome/pull/9148 merged into ESPHome version **2025.6.1** please update and don't use temporary solution described here.

~~Fixed in version [1.0.13](https://github.com/myhomeiot/esphome-components/releases/tag/1.0.13) but required https://github.com/esphome/esphome/pull/9148, if you  don't want to wait this PR to be merged in order to apply this PR you can use following ESPHome configuration:~~
```yaml
external_components:
  - source: github://myhomeiot/esphome-components
  - source: github://pr#9148
    components: [esp32_ble_tracker]
```

**Don't forget to remove this configuration after this PR will be merged!**

Update: Looks like PR https://github.com/esphome/esphome/pull/9148 will be merged in next ESPHome version 2025.6.1.

**Comment by mccaffm** [comment]
(inkyenv) pi@piw1:~/inky/examples $
(inkyenv) pi@piw1:~/inky/examples $ python3 name-badge.py --colour red --name "Test Badge"
Traceback (most recent call last):
  File "/home/pi/inky/examples/name-badge.py", line 7, in <module>
    from font_intuitive import Intuitive
ModuleNotFoundError: No module named 'font_intuitive'

**Comment by mccaffm** [comment]
(inkyenv) pi@piw1:~/inky/examples $ python3 name-badge.py --colour red --name "Test Badge"
Traceback (most recent call last):
  File "/home/pi/inky/examples/name-badge.py", line 10, in <module>
    from inky.auto import auto
ModuleNotFoundError: No module named 'inky'

**Comment by oopiicaa** [comment]
**Irrelevant - solved: I removed old PR for external_components in my config, which was already merged at some point.**

I'm getting this after trying upgrading from 2025.5.2 to 2025.6.1:
```
INFO ESPHome 2025.6.1
INFO Reading configuration /config/esphome/esp32-new-1.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esp32-new-1 (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.4
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.3.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.6
Compiling .pioenvs/esp32-new-1/src/esphome/components/ble_gateway/ble_gateway.cpp.o
Compiling .pioenvs/esp32-new-1/src/esphome/components/captive_portal/captive_portal.cpp.o
Compiling .pioenvs/esp32-new-1/src/esphome/components/esp32/core.cpp.o
Compiling .pioenvs/esp32-new-1/src/esphome/components/esp32/gpio.cpp.o
Compiling .pioenvs/esp32-new-1/src/esphome/components/esp32/preferences.cpp.o
In file included from src/esphome/components/ble_gateway/ble_gateway.cpp:3:
src/esphome/components/ble_gateway/ble_gateway.h:25:58: error: 'esp32_ble' does not name a type
   static std::string scan_result_to_hci_packet_hex(const esp32_ble::BLEScanResult &scan_result);
                                                          ^~~~~~~~~
src/esphome/components/ble_gateway/ble_gateway.h:25:83: error: expected unqualified-id before '&' token
   static std::string scan_result_to_hci_packet_hex(const esp32_ble::BLEScanResult &scan_result);
                                                                                   ^
src/esphome/components/ble_gateway/ble_gateway.h:25:82: error: expected ')' before '&' token
   static std::string scan_result_to_hci_packet_hex(const esp32_ble::BLEScanResult &scan_result);
                                                   ~                              ^~
                                                                                  )
src/esphome/components/ble_gateway/ble_gateway.h:25:83: error: static member function 'static std::__cxx11::string esphome::ble_gateway::BLEGateway::scan_result_to_hci_packet_hex(...)' cannot have ref-qualifier
   static std::string scan_result_to_hci_packet_hex(const esp32_ble::BLEScanResult &scan_result);
                                                                                   ^
src/esphome/components/ble_gateway/ble_gateway.h:25:83: error: expected ';' at end of member declaration
   static std::string scan_result_to_hci_packet_hex(const esp32_ble::BLEScanResult &scan_result);
                                                                                   ^
                                                                                    ;
src/esphome/components/ble_gateway/ble_gateway.h:25:84: error: 'scan_result' does not name a type
   static std::string scan_result_to_hci_packet_hex(const esp32_ble::BLEScanResult &scan_result);
                                                                                    ^~~~~~~~~~~
src/esphome/components/ble_gateway/ble_gateway.cpp:15:61: error: 'esp32_ble' does not name a type
 std::string BLEGateway::scan_result_to_hci_packet_hex(const esp32_ble::BLEScanResult &scan_result) {
                                                             ^~~~~~~~~
src/esphome/components/ble_gateway/ble_gateway.cpp:15:86: error: expected unqualified-id before '&' token
 std::string BLEGateway::scan_result_to_hci_packet_hex(const esp32_ble::BLEScanResult &scan_result) {
                                                                                      ^
src/esphome/components/ble_gateway/ble_gateway.cpp:15:85: error: expected ')' before '&' token
 std::string BLEGateway::scan_result_to_hci_packet_hex(const esp32_ble::BLEScanResult &scan_result) {
                                                      ~                              ^~
                                                                                     )
src/esphome/components/ble_gateway/ble_gateway.cpp:15:87: error: expected initializer before 'scan_result'
 std::string BLEGateway::scan_result_to_hci_packet_hex(const esp32_ble::BLEScanResult &scan_result) {
                                                                                       ^~~~~~~~~~~
Compiling .pioenvs/esp32-new-1/src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp.o
*** [.pioenvs/esp32-new-1/src/esphome/components/ble_gateway/ble_gateway.cpp.o] Error 1
========================== [FAILED] Took 2.59 seconds ==========================
```

Config:
```
esphome:
  name: esp32-new-1
  friendly_name: esp32-new-1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: redacted

ota:
  - platform: esphome
    password: redacted

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-New-1 Fallback Hotspot"
    password: "redacted"

captive_portal:

switch:
  - platform: restart
    name: "ESP new 1 BLE Passive restart"  

external_components:
  - source: github://myhomeiot/esphome-components
  - source: github://pr#2854
    components: [esp32_ble_tracker]

esp32_ble_tracker:

ble_gateway:
  devices:
    - mac_address: redacted
  on_ble_advertise:
    then:
      homeassistant.event:
        event: esphome.on_ble_advertise
        data:
          packet: !lambda return packet;
```
