### ISSUE TITLE
BLE Beacon Devices

### ISSUE THREAD

**Issue by dmamontov** [myhomeiot/esphome-components#4]
I would like to be able to also transmit the packet by UUID beacon and not just by mac address in BLE Gateway. Was there such a plan?

**Comment by myhomeiot** [comment]
Currently BLE Gateway works only with [Passive BLE Monitor](https://github.com/custom-components/ble_monitor), which AFAIK doesn't support device definition by UUID and requires MAC address. What you plan to do in Home Assistant with raw BLE HCI packet received and transferred by BLE Gateway to Home Assistant?

**Comment by dmamontov** [comment]
Yes, I plan to refine it, I suggest debugging this request as I finalize it. At the moment, I made a PR with the transfer of the gateway id https://github.com/custom-components/ble_monitor/pull/636

Since I started a big project to define rooms in conjunction with your component and Passive BLE Monitor. I will post the first alpha version of the component soon.

Just for the future, I wanted to know if there is such an opportunity in esphome itself.

Thank you. I'll let you know when the mod is ready.

**Comment by dmamontov** [comment]
As I have promised. Released iBeacon support into beta: https://github.com/custom-components/ble_monitor/releases/tag/7.3.0-beta

**Comment by myhomeiot** [comment]
> As I have promised. Released iBeacon support into beta: https://github.com/custom-components/ble_monitor/releases/tag/7.3.0-beta

Great! Did you manage to filter packets by service UUID or you need dedicated beacon UUID filter?

**Comment by myhomeiot** [comment]
@dmamontov I don't have Beacon to test but I'm confident that you can use this code in order to filter and send packets only for beacon devices (in this code you can also add check for specific UUID):
```
esp32_ble_tracker:
  on_ble_advertise:
    then:
      - if:
          condition:
            lambda: return x.get_ibeacon().has_value();
          then:
            - lambda: |-
                if (x.get_ibeacon().has_value()) {
                  auto ibeacon = x.get_ibeacon().value();
                  ESP_LOGD("iBeacon", "iBeacon data:");
                  ESP_LOGD("iBeacon", "  UUID: %s", ibeacon.get_uuid().to_string().c_str());
                  ESP_LOGD("iBeacon", "  Major: %u", ibeacon.get_major());
                  ESP_LOGD("iBeacon", "  Minor: %u", ibeacon.get_minor());
                  ESP_LOGD("iBeacon", "  TXPower: %d", ibeacon.get_signal_power());
                }
            - homeassistant.event:
                event: esphome.on_ble_advertise
                data:
                  packet: !lambda return ble_gateway::BLEGateway::scan_result_to_hci_packet_hex(x.get_scan_result());
```

**Comment by dmamontov** [comment]
I'll check today, just today the manufacturer wanted to debug a new one.

**Comment by dmamontov** [comment]
@myhomeiot
This is how it works, but the uuid returned is not correct in the log.
BBFB5D85-5E46-5D89-DF49-C18E887662F1 instead of F1627688-8EC1-49DF-895D-465E855DFBBB apparently the order is reversed.

But the package is correct.

It still lacks a full filter. Otherwise, I have a lot of beacons in my house in other apartments, and it catches everything).
```yaml
esp32_ble_tracker:
  on_ble_advertise:
    then:
      - if:
          condition:
            lambda: return x.get_ibeacon().has_value();
          then:
            - lambda: |-
                if (x.get_ibeacon().has_value()) {
                  auto ibeacon = x.get_ibeacon().value();
                  ESP_LOGD("iBeacon", "iBeacon data:");
                  ESP_LOGD("iBeacon", "  UUID: %s", ibeacon.get_uuid().to_string().c_str());
                  ESP_LOGD("iBeacon", "  Major: %u", ibeacon.get_major());
                  ESP_LOGD("iBeacon", "  Minor: %u", ibeacon.get_minor());
                  ESP_LOGD("iBeacon", "  TXPower: %d", ibeacon.get_signal_power());
                  ESP_LOGD("iBeacon", "  Packet: %s", ble_gateway::BLEGateway::scan_result_to_hci_packet_hex(x.get_scan_result()).c_str());
                }
            - homeassistant.event:
                event: esphome.on_ble_advertise
                data:
                  packet: !lambda return ble_gateway::BLEGateway::scan_result_to_hci_packet_hex(x.get_scan_result());
```

There is software for ibeacon emulation on phones:
Android: [Beacon Simulator](https://play.google.com/store/apps/details?id=net.alea.beaconsimulator), [Home Assistant Companion](https://play.google.com/store/apps/details?id=io.homeassistant.companion.android)
iOS: [Locate Beacon](https://apps.apple.com/ru/app/locate-beacon/id738709014)
